### PR TITLE
646 ab labeling of tests

### PR DESCRIPTION
**Pull request by Core5563**

### CODE REVIEW

**Comment by Core5563** [comment]
please check if "branch creation" and "first label" is done correctly

**Comment by EagleoutIce** [comment]
I changed the merge target to dataflow V2, besides this it seems to be fine :)

**Comment by EagleoutIce** [comment]
Similarly to #654 i claim this.

**Comment by EagleoutIce** [comment]
_This pull request is included in v2.0.0 (see [Release v2.0.0 (Dataflow v2)](https://github.com/Code-Inspect/flowr/releases/tag/v2.0.0))._

**Comment by EagleoutIce** [comment]
_This pull request is included in v2.0.0 (see [Release v2.0.0 (Dataflow v2)](https://github.com/Code-Inspect/flowr/releases/tag/v2.0.0))._

**Pull request merged**
