### PR TITLE
Make it clearer, where to find linting information in the wiki

### PR DESCRIPTION
**Pull request by EagleoutIce**

### CODE REVIEW

**Comment by EagleoutIce** [comment]
@Ehcsan, do you think that this makes it easier to know how to deal with the linter?

**Comment by Ehcsan** [comment]
The changes make it easier to find information about the linter in its dedicated section. However while checking the changes I noticed that the wiki table of contend only redirects you to the home page (at least on the mobile version in chrome).

**Review by Ehcsan — APPROVED** [review]
The changes make the information about the linter easier to find

**Comment by EagleoutIce** [comment]
> However while checking the changes I noticed that the wiki table of contend only redirects you to the home page (at least on the mobile version in chrome).

Yes, this is only until we merge this and the new wiki pages get deployed :)

**Review by LukasPietzschmann — APPROVED** [review]

**Pull request merged**
