### PR TITLE
lint: add curly rule and fix curly braces

### PR DESCRIPTION
**Pull request by Ellpeck**

### CODE REVIEW

**Comment by Ellpeck** [comment]
@EagleoutIce we have to think about implementing a consistent brace style (see https://eslint.org/docs/latest/rules/brace-style) because right now, this PR causes the `--fix` action to create some *wild* formatting.

Let me know if we should make that part of this PR or open another issue for it!

**Comment by EagleoutIce** [comment]
I think it should be part of this PR because otherwise fix makes the code... urgh

**Comment by EagleoutIce** [comment]
I want the #onetruebracestyle

**Review by EagleoutIce — APPROVED** [review]

**Comment by EagleoutIce** [comment]
_This pull request is included in v1.4.2 (see [Release v1.4.2 (Dropping xmlparsedata, Benchmark Re-Runs, and Repl Fixes)](https://github.com/Code-Inspect/flowr/releases/tag/v1.4.2))._

**Pull request merged**
